### ISSUE TITLE
Add Splash Screen

### ISSUE THREAD

**Issue by valtlfelipe** [valtlfelipe/statuscenter#1]
Add a splash screen, maybe with just the logo, so that there is no white blank screen on loading the app

**Comment by EANimesha** [comment]
I will do this. Assign me

**Comment by valtlfelipe** [comment]
Forgot to add, if needed, this is the flutter doc https://flutter.dev/docs/development/ui/advanced/splash-screen

**Comment by EANimesha** [comment]
Can I use a flutter package splash screen [https://pub.dev/packages/splashscreen](url)  ?
It will be more easier

**Comment by valtlfelipe** [comment]
Actually the idea was to do the native way like in the docs, to avoid the empty blank screen when flutter is initialising. Using this widget would not resolve this.
This maybe can help you https://pub.dev/packages/flutter_native_splash. Have a look at it. 

If you need any help, please let me know.

**Comment by EANimesha** [comment]
@valtlfelipe I made a PR can you check?

**Comment by valtlfelipe** [comment]
Sorry @EANimesha for taking so much time. Just reviewed, have a look. Just 2 small things to fix.

Thanks fr your contribution!

**Comment by EANimesha** [comment]
> Sorry @EANimesha for taking so much time. Just reviewed, have a look. Just 2 small things to fix.
> 
> Thanks fr your contribution!

@valtlfelipe updated the PR

**Comment by valtlfelipe** [comment]
closed by #6
