### ISSUE TITLE
Delete incident

### ISSUE THREAD

**Issue by valtlfelipe** [valtlfelipe/statuscenter#3]
Add option to be able to delete an incident.
Statuspage API doc: https://developer.statuspage.io/#operation/deletePagesPageIdIncidentsIncidentId

Would be nice to have a confirmation dialog before removing.

**Comment by navinkumar-k-015** [comment]
I have solved this issue but I am unable to create a branch and pull request, it says
Permission to valtlfelipe/statuscenter.git denied to navinkumar-k-015.

**Comment by valtlfelipe** [comment]
hi @navinkumar-k-015! Awesome, thanks!

You have to fork this repo to your user account, and from there open a pull request to this repo. Have a look here https://www.digitalocean.com/community/tutorials/hacktoberfest-how-to-submit-your-first-pull-request-on-github#cloning-a-repository

Please let me know if you need further assistance.

**Comment by navinkumar-k-015** [comment]
Yeah I already forked it but it still gives me same problem

**Comment by valtlfelipe** [comment]
Maybe your origin is set to this repo, and not the fork. You may have cloned this repo instead of your fork.
Try this:
```
git remote rm origin
git remote add origin https://github.com/user/FORK.git
```

Where `user/FORK` is the url to your fork on your account. Should be something like this `navinkumar-k-015/statuscenter`
